# Generated by Django 5.1 on 2024-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('arrived', 'Arrived at Location'), ('providing', 'Providing Service'), ('completed', 'Service Completed'), ('cancelled', 'Cancelled')], max_length=20)),
            ],
        ),
    ]
